//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public int FromCityID { get; set; }
        public int ToCityID { get; set; }
        public System.TimeSpan Depart { get; set; }
        public System.TimeSpan Arrives { get; set; }
        public Nullable<int> LayoverCityID { get; set; }
        public Nullable<System.TimeSpan> LayoverTime { get; set; }
        public decimal Price { get; set; }
        public int AirlineID { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual City City2 { get; set; }
    }
}
